name = "Friends RPG Server"
author = "Nickleberry1"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57ab5da2ef5415e427595c8bc9725bd8537fd97dec0c238f3e7bcea1944ecd99"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
